version: "3.8"
services:
  postgres:
    image: "postgres:15.6"
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=GestionEmpresa
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d